name: Account-workflow

on:
    push:
        branches:
            - account
        paths:
            - '**'
    workflow_dispatch:

jobs:
    getCode:
        runs-on: Ubuntu-latest
        steps:
            - name: First step
              run: echo "account workflow"