name: api-gateway-workflow

on:
    push:
        branches:
            - gateway
        paths:
            - '**'
    workflow_dispatch:

jobs:
    getCode:
        runs-on: Ubuntu-latest
        steps:
            - name: First step
              run: echo "API-gateway"