name: Auth-workflow

on:
    push:
        branches:
            - auth
        paths:
            - '**'
    workflow_dispatch:

jobs:
  getCode:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Echo for auth branch push
        if: github.ref == 'refs/heads/auth'
        run: echo "Authentication workflow triggered by push to 'auth' branch"