name: Fraud-workflow

on:
    push:
        branches:
            - fraud
        paths:
            - '**'
    workflow_dispatch:

jobs:
    getCode:
        runs-on: Ubuntu-latest
        steps:
            - name: First step
              run: echo "Fraud-workflow"