name: notification-workflow

on:
    push:
        branches:
            - notification
    pull_request:
        types: [opened, closed, auto_merge_enabled]
    workflow_dispatch:

jobs:
    getCode:
        runs-on: Ubuntu-latest