name: payment-workflow

on:
    push:
        branches:
            - payment
    pull_request:
        types: [opened, closed, auto_merge_enabled]
    workflow_dispatch:

jobs:
    getCode:
        runs-on: Ubuntu-latest
        steps:
            - name: First step
              run: echo "payment-workflow"