name: Deploy-to-VPS-workflow

on:
    push:
        branches:
            - main
        paths:
            - '**'
    workflow_dispatch:

jobs:
    getCode:
        runs-on: Ubuntu-latest
        steps:
            - name: First step
              run: echo "Production workflow"