name: search-workflow

on:
    push:
        branches:
            - search
        paths:
            - '**'
    workflow_dispatch:

jobs:
    getCode:
        runs-on: Ubuntu-latest
        steps:
            - name: First step
              run: echo "search-workflow"